const language2text = {
af:'Afrikaans',
ar:'اللغة العربية',
az:'Azərbaycan',
bg:'български',
ca:'català',
ckb:'کوردی',
cs:'čeština',
da:'Dansk',
de:'Deutsch',
el:'Ελληνικά',
en:'English',
es:'Español',
et:'eesti',
fa:'فارسی',
fi:'suomi',
fr:'Français',
he:'עברית',
hr:'hrvatski jezik',
hu:'magyar',
id:'Indonesian',
it:'Italiano',
ja:'日本語',
ko:'한국어',
lt:'lietuvių kalba',
lv:'latviešu valoda',
nl:'Nederlands',
no:'Norsk',
pl:'język polski',
pt:'Português',
ro:'Română',
ru:'Русский',
sk:'slovenčina',
sl:'slovenski jezik',
srCyrl:'српски језик',
srLatn:'srpski jezik',
sv:'svenska',
th:'ไทย',
tr:'Türkçe',
uk:'Українська',
vi:'Tiếng Việt',
zhHans:'中文',
zhHant:'正體中文',
}

Object.freeze(language2text)
export default language2text